services:
  postgres:
    image: postgres:18
    container_name: scheme-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: scheme_db
      POSTGRES_USER: scheme_user
      POSTGRES_PASSWORD: scheme_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: