"""add state column to schemes

Revision ID: b08d40047bc5
Revises: 5d2f7b84e13c
Create Date: 2026-08-13 23:46:52.896518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08d40047bc5'
down_revision: Union[str, Sequence[str], None] = '5d2f7b84e13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('benefits_scheme_id_fkey'), 'benefits', type_='foreignkey')
    op.create_foreign_key(None, 'benefits', 'schemes', ['scheme_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('eligibility_rules_scheme_id_fkey'), 'eligibility_rules', type_='foreignkey')
    op.create_foreign_key(None, 'eligibility_rules', 'schemes', ['scheme_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('official_sources_scheme_id_fkey'), 'official_sources', type_='foreignkey')
    op.create_foreign_key(None, 'official_sources', 'schemes', ['scheme_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('required_documents_scheme_id_fkey'), 'required_documents', type_='foreignkey')
    op.create_foreign_key(None, 'required_documents', 'schemes', ['scheme_id'], ['id'], ondelete='CASCADE')
    op.add_column('schemes', sa.Column('state', sa.String(length=100), server_default='ALL_INDIA', nullable=False))
    op.create_index(op.f('ix_schemes_state'), 'schemes', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schemes_state'), table_name='schemes')
    op.drop_column('schemes', 'state')
    op.drop_constraint(None, 'required_documents', type_='foreignkey')
    op.create_foreign_key(op.f('required_documents_scheme_id_fkey'), 'required_documents', 'schemes', ['scheme_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'official_sources', type_='foreignkey')
    op.create_foreign_key(op.f('official_sources_scheme_id_fkey'), 'official_sources', 'schemes', ['scheme_id'], ['id'])
    op.drop_constraint(None, 'eligibility_rules', type_='foreignkey')
    op.create_foreign_key(op.f('eligibility_rules_scheme_id_fkey'), 'eligibility_rules', 'schemes', ['scheme_id'], ['id'])
    op.drop_constraint(None, 'benefits', type_='foreignkey')
    op.create_foreign_key(op.f('benefits_scheme_id_fkey'), 'benefits', 'schemes', ['scheme_id'], ['id'])
    # ### end Alembic commands ###
