"""add_saas_3tier_uids_life_stage_and_member_vault_linking

Revision ID: 29988c11624f
Revises: 3f5c4e68a900
Create Date: 2026-08-14 17:43:38.103268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29988c11624f'
down_revision: Union[str, Sequence[str], None] = '3f5c4e68a900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_members', sa.Column('citizen_uid', sa.String(length=50), nullable=False))
    op.add_column('household_members', sa.Column('member_uid', sa.String(length=50), nullable=False))
    op.add_column('household_members', sa.Column('household_uid', sa.String(length=50), nullable=False))
    op.add_column('household_members', sa.Column('life_stage', sa.String(length=20), server_default='ADULT', nullable=False))
    op.add_column('household_members', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('household_members', sa.Column('caste_category', sa.String(length=50), nullable=True))
    op.add_column('household_members', sa.Column('annual_income', sa.Float(), nullable=True))
    op.add_column('household_members', sa.Column('verification_status', sa.String(length=50), server_default='UNVERIFIED', nullable=False))
    op.add_column('household_members', sa.Column('aadhaar_last_four', sa.String(length=4), nullable=True))
    op.create_index(op.f('ix_household_members_citizen_uid'), 'household_members', ['citizen_uid'], unique=True)
    op.create_index(op.f('ix_household_members_household_uid'), 'household_members', ['household_uid'], unique=False)
    op.create_index(op.f('ix_household_members_life_stage'), 'household_members', ['life_stage'], unique=False)
    op.create_index(op.f('ix_household_members_member_uid'), 'household_members', ['member_uid'], unique=True)
    op.create_index(op.f('ix_household_members_verification_status'), 'household_members', ['verification_status'], unique=False)
    op.add_column('user_documents', sa.Column('household_member_id', sa.Integer(), nullable=True))
    op.add_column('user_documents', sa.Column('citizen_uid', sa.String(length=50), nullable=True))
    op.add_column('user_documents', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_documents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_documents_citizen_uid'), 'user_documents', ['citizen_uid'], unique=False)
    op.create_index(op.f('ix_user_documents_household_member_id'), 'user_documents', ['household_member_id'], unique=False)
    op.create_foreign_key(None, 'user_documents', 'household_members', ['household_member_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user_documents', 'created_at')
    op.drop_column('user_documents', 'updated_at')
    op.add_column('users', sa.Column('citizen_uid', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('household_uid', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_citizen_uid'), 'users', ['citizen_uid'], unique=True)
    op.create_index(op.f('ix_users_household_uid'), 'users', ['household_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_household_uid'), table_name='users')
    op.drop_index(op.f('ix_users_citizen_uid'), table_name='users')
    op.drop_column('users', 'household_uid')
    op.drop_column('users', 'citizen_uid')
    op.add_column('user_documents', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('user_documents', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_documents', type_='foreignkey')
    op.drop_index(op.f('ix_user_documents_household_member_id'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_citizen_uid'), table_name='user_documents')
    op.drop_column('user_documents', 'verified_at')
    op.drop_column('user_documents', 'uploaded_at')
    op.drop_column('user_documents', 'citizen_uid')
    op.drop_column('user_documents', 'household_member_id')
    op.drop_index(op.f('ix_household_members_verification_status'), table_name='household_members')
    op.drop_index(op.f('ix_household_members_member_uid'), table_name='household_members')
    op.drop_index(op.f('ix_household_members_life_stage'), table_name='household_members')
    op.drop_index(op.f('ix_household_members_household_uid'), table_name='household_members')
    op.drop_index(op.f('ix_household_members_citizen_uid'), table_name='household_members')
    op.drop_column('household_members', 'aadhaar_last_four')
    op.drop_column('household_members', 'verification_status')
    op.drop_column('household_members', 'annual_income')
    op.drop_column('household_members', 'caste_category')
    op.drop_column('household_members', 'date_of_birth')
    op.drop_column('household_members', 'life_stage')
    op.drop_column('household_members', 'household_uid')
    op.drop_column('household_members', 'member_uid')
    op.drop_column('household_members', 'citizen_uid')
    # ### end Alembic commands ###
