"""add policy versioning and decision records

Revision ID: 71a656b0a5b9
Revises: 29988c11624f
Create Date: 2026-09-03 19:04:38.179121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a656b0a5b9'
down_revision: Union[str, Sequence[str], None] = '29988c11624f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('family_id', sa.String(length=100), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('scheme_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_hash', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_versions_scheme_id'), 'scheme_versions', ['scheme_id'], unique=False)
    op.create_table('eligibility_rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_version_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_rule_versions_scheme_version_id'), 'eligibility_rule_versions', ['scheme_version_id'], unique=False)
    op.execute("DELETE FROM chat_sessions WHERE user_id IS NULL")
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('citizen_facts', sa.Column('source_type', sa.String(length=50), server_default='self_attested', nullable=False))
    op.add_column('citizen_facts', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('citizen_facts', sa.Column('status', sa.String(length=50), server_default='unverified', nullable=False))
    op.add_column('citizen_facts', sa.Column('supersedes_fact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'citizen_facts', 'citizen_facts', ['supersedes_fact_id'], ['id'], ondelete='SET NULL')
    op.add_column('schemes', sa.Column('publication_state', sa.String(length=50), server_default='published', nullable=False))
    op.add_column('schemes', sa.Column('source_freshness', sa.String(length=50), server_default='fresh', nullable=False))
    op.create_index(op.f('ix_schemes_publication_state'), 'schemes', ['publication_state'], unique=False)
    op.create_index(op.f('ix_schemes_source_freshness'), 'schemes', ['source_freshness'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schemes_source_freshness'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_publication_state'), table_name='schemes')
    op.drop_column('schemes', 'source_freshness')
    op.drop_column('schemes', 'publication_state')
    op.drop_constraint(None, 'citizen_facts', type_='foreignkey')
    op.drop_column('citizen_facts', 'supersedes_fact_id')
    op.drop_column('citizen_facts', 'status')
    op.drop_column('citizen_facts', 'confidence_score')
    op.drop_column('citizen_facts', 'source_type')
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_eligibility_rule_versions_scheme_version_id'), table_name='eligibility_rule_versions')
    op.drop_table('eligibility_rule_versions')
    op.drop_index(op.f('ix_scheme_versions_scheme_id'), table_name='scheme_versions')
    op.drop_table('scheme_versions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
